### ISSUE TITLE
How to listen to didSelectRowAt event for NonExpandableCell 

### ISSUE THREAD

**Issue by kohdesmond** [younatics/YNExpandableCell#1]
HI YN, good git!

just wondering how do you listen to didSelectRowAt event for NonExpandableCell ?

cheers

des

**Comment by younatics** [comment]
Hello @kohdesmond,
I will make that function today.
I will close this issue if I done it. 

Cheers,
Younatics

**Comment by younatics** [comment]
I made delegate for you 👍 
see [v0.3.0](https://github.com/younatics/YNExpandableCell/releases/tag/0.3.0)

**Comment by kohdesmond** [comment]
Sweet thanks! it works!

**Comment by kohdesmond** [comment]
@younatics the didSelectRow was not called when expanded cell closed

**Comment by younatics** [comment]
I will check it again

**Comment by kohdesmond** [comment]
` public func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {`

was called when closing the expanding cell, but delegate was not called

**Comment by younatics** [comment]
I will make didSelectRowAt delegate too! 👍 
I will tell you if it is finished

**Comment by kohdesmond** [comment]
+1

**Comment by younatics** [comment]
I made didDeselectRowAt delegate. 
see [v0.5.0](https://github.com/younatics/YNExpandableCell/releases/tag/0.5.0)
Cheers!
