### ISSUE TITLE
How to define a nonExpandablecell from a nib?

### ISSUE THREAD

**Issue by kohdesmond** [younatics/YNExpandableCell#11]
Hi YN,

As above.

you used an example  
`let nonExpandablecell = tableView.dequeueReusableCell(withIdentifier: "YNNonExpandableCell")`

but i want to use a nib file as one of the nonExpandablecell. what should i do?

Cheers

Desmond

**Comment by kohdesmond** [comment]
don worry about it. i got it fixed.

Cheers

Desmond

**Comment by younatics** [comment]
Great!
