### ISSUE TITLE
Expand only one cell?

### ISSUE THREAD

**Issue by mla2c** [younatics/YNExpandableCell#13]
Is it possible to expand only one cell and automatically close the previuosly expanded cell (if there is one)?

**Comment by nathankonrad1** [comment]
@mla2c @younatics @lyuxxx 
Hey Guys, 
Any update for this question? 
I am interested also...

Thanks in advance ;)

**Comment by mla2c** [comment]
Best I could do was to implement the following UITableViewDelegate Method in YNTableView

    public func tableView(_ tableView: UITableView, willSelectRowAt indexPath: IndexPath) -> IndexPath? {
        if let cell = tableView.cellForRow(at: indexPath) {
            if let view = tableView as? YNTableView {
                view.collapseAll()
            }          
            let pointInTable = cell.convert(cell.bounds.origin, to: tableView)
            let newIndexPath = tableView.indexPathForRow(at: pointInTable)
            return newIndexPath
        }
        
        return indexPath
    }

It does not work too well, though. Repeated re-expanding of rows showed stale content for a short moment. But I think this is another problem due to dequeing of reusable cells. 

If you find a workable solution, by all means post it here, please.

**Comment by jboteros** [comment]
@mla2c @younatics @lyuxxx

Hi,
Any update for this question?

I am need sow only one cell at time ...
Thanks  ;)

**Comment by jboteros** [comment]
@nathankonrad1 Hi, how are you? You managed to show only one at a time. Thank you

**Comment by younatics** [comment]
@mla2c  will be right in this repository.
Thanks!

**Comment by kohdesmond** [comment]
@younatics any updates on it?

**Comment by younatics** [comment]
I started to make another library for YNExpandable v2. I will give you a link within a week.   Thanks!

**Comment by younatics** [comment]
Hello. Thank you for your great patience. I made [ExpandableCell](https://github.com/younatics/ExpandableCell) fully refactored YNExpandableCell.  

Thanks!
