### ISSUE TITLE
compromise between row select and expandability.

### ISSUE THREAD

**Issue by wdcurry** [younatics/YNExpandableCell#14]
This might prove an awesome repo for me if the following is either do-able right now, or possible:

Show a set of rows, some expandable, some not BUT, expansion only occurs if the + button is tapped. Selection of the row itself should be as normal.

I will dig through the code to see if i can figure out if this is implemented.

**Comment by younatics** [comment]
You can clone and change `didSelectrow` to other function. Thanks!
