### ISSUE TITLE
2 layout bugs discovered

### ISSUE THREAD

**Issue by Icy1337** [younatics/YNExpandableCell#18]
Hey, first of all thank you for this awesome framework im currently using it in one of my projects.

i discovered two minor yet annoying bugs in the layout of the cells, the first one is happens when expanding the one before last cell, you can see its content show up in the last cell, here's the GIF link demonstration : 
![whimsicaleachivorybilledwoodpecker-size_restricted](https://user-images.githubusercontent.com/10535208/29876109-3ecb3adc-8d72-11e7-93e3-848f27bd1e18.gif)

second bug happens if user multiclick a lot of the cells in a short period of time it basically messes up the layout, here's the GIF link demonstration : 
![glamoroustornibadanmalimbe-size_restricted](https://user-images.githubusercontent.com/10535208/29876129-4be2ccb2-8d72-11e7-87cb-aeee731c4fcf.gif)

**Comment by younatics** [comment]
Hello, How about using [ExpandableCell](https://github.com/younatics/ExpandableCell)?

**Comment by Icy1337** [comment]
damn i didn't know it, i will try it now.
