### ISSUE TITLE
Cannot inherit from non-open class 'YNExpandableCell' outside of its defining module

### ISSUE THREAD

**Issue by kohdesmond** [younatics/YNExpandableCell#3]
Hi @younatics,

just a weird thing

I have to change line 12 of YNTableViewCell.swift from:
`public class YNExpandableCell: UITableViewCell {` into `open class YNExpandableCell: UITableViewCell {`

AND

`public override func awakeFromNib() {` into `open override func awakeFromNib() {`

to eliminate the error.

not too sure if is an module issues.

**Comment by younatics** [comment]
I will check and answer it ASAP

**Comment by younatics** [comment]
Hi @kohdesmond,

Probably, you tried to subclass my class. 
I changed every `public` class to `open` class so you can use it right now :)
See [v0.4.0](https://github.com/younatics/YNExpandableCell/releases/tag/0.4.0)

Please reopen this issue if it still doesn't work

Thanks,
younatics

**Comment by kohdesmond** [comment]
Cheers, thanks.
Swift 3.0 are more restrictive but better

**Comment by younatics** [comment]
I totally agree with you :)
