### ISSUE TITLE
anyway to open up the animation?

### ISSUE THREAD

**Issue by kohdesmond** [younatics/YNExpandableCell#4]
This is more of a major enhancement. But food for thought.

i wonder if you can open up the + & - animation for other images and purposes?
say expand for more details indicator
![screen shot 2017-03-21 at 11 12 59](https://cloud.githubusercontent.com/assets/1192544/24131189/083f7fc4-0e28-11e7-878d-70f1fcaa8c5c.png)

Once I tap open, it will rotate the arrow pointing up and vice versa 

![screen shot 2017-03-21 at 11 16 44](https://cloud.githubusercontent.com/assets/1192544/24131187/05e82f64-0e28-11e7-80fa-fe2908b447ba.png)

**Comment by younatics** [comment]
Great idea. I will try it to make other `YNExpandableCell` or you can make pull request for me.
Whatever, I'll do this evening but not now! :)

**Comment by younatics** [comment]
I will close this issue :)
