### ISSUE TITLE
Add support for multiple cells in expansion

### ISSUE THREAD

**Issue by dimovskidamjan** [younatics/YNExpandableCell#6]
A really useful addition would be for us to be able to expand multiple cells on tap, which is really useful for screens containing selecting multiple options, checklists, etc. If it's possible, please implement this. Thanks :)

**Comment by younatics** [comment]
After I finished this feature, I will comment it again :)

**Comment by younatics** [comment]
Hello @dimovskidamjan ,
I'm sorry to tell you that.. this project was designed to expand only one cell :( 
I will made another open source after I get some more time. 
Thank you!

**Comment by younatics** [comment]
Hello. Thank you for your great patience. I made [ExpandableCell](https://github.com/younatics/ExpandableCell) fully refactored YNExpandableCell.  

Thanks!
