### ISSUE TITLE
overriding the heightForRowAtIndex doesn't seem to work. 

### ISSUE THREAD

**Issue by johndpope** [younatics/YNExpandableCell#7]
In my tableview - my expandable cell needs to be larger than > 44 pixels in height.
They are 200 I need to expand to 350. 

perhaps you could provide a method to check cell for initial height....

<img width="1158" alt="screen shot 2017-04-07 at 3 23 37 pm" src="https://cloud.githubusercontent.com/assets/289994/24816320/3a126288-1ba6-11e7-8960-f4e814d1e49a.png">

    // this is obvious fix - but then the expanded cells don't get correct height 
    open func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        guard let delegate = self.ynDelegate else {return UITableViewAutomaticDimension}
        guard let heightForRow = delegate.tableView(self, heightForRowAt: indexPath)  else {
                print("height will be 44")
                return UITableViewAutomaticDimension
        }
        return heightForRow
    }

fyi - I'm using it to expand a text section.

**Comment by younatics** [comment]
I will made that method.

**Comment by younatics** [comment]
Hello @johndpope I published [v1.0.0](https://github.com/younatics/YNExpandableCell/releases/tag/1.0.0)
Please use this method with your height. 

Cheers!

**Comment by johndpope** [comment]
thanks
