### ISSUE TITLE
Reload particular Cell's View

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [younatics/YNExpandableCell#9]
I want to reload particular cell & even its attached expandable view.

How can I do this?

**Comment by younatics** [comment]
Hello @Rashesh-Bosamiya, 
Is there any problem when you use `reloadData` function?

**Comment by Rashesh-Bosamiya** [comment]
Actually I am using this library for showing filter options.

I have 7 different filters in each cell. Each filter has option to choose, when user choose any option from any cell's attached view, I have to reload whole tableView to highlight selected option.

Here is the problem, where I reload the whole tableView. It causes too much of dwindled performance.

So it's better to reload particular cell which needs refresh.

**Comment by younatics** [comment]
Hello @Rashesh-Bosamiya,
Maybe you can `beginUpdate` and `reloadRowsAtIndexPaths` and `endUpdate`
Is it helpful for you?

**Comment by Rashesh-Bosamiya** [comment]
I have tried `reloadRowsAtIndexPaths, but this reload only cell(s) not attached UIView's.

But not with `beginUpdate` & `endUpdate`.

I'll try with `beginUpdate` & `endUpdate` & inform you.


But you got my problem right?

**Comment by younatics** [comment]
Sure. I fully understand what you mean. If you can't do this, I will try in this weekend.
Cheers!

**Comment by Rashesh-Bosamiya** [comment]
My suggestion.

Can we have a method like `tableView.expandCell(at indexPath:IndexPath)`?

That expand particular cell programmatically. informally we can achieve our goal to reload particular cell and its attached expandable view as well.

`self.tableView.expandAll()` kind of similar to this function.

**Comment by Rashesh-Bosamiya** [comment]
Finally, I found out!

I just need to call `reloadRowsAtIndexPaths`.

The problem was:

I was passing incorrect indexPath in `reloadRowsAtIndexPaths` function.

I have `return 6` in `numberOfRowsInSection` method.

Now, this library internally makes `double` `numberOfRowsInSection` as addition to expandable element.

Now if I want to reload `6th` row, I just need to call `tableView.reloadRows(at: [IndexPath(row: 6, section: 0)], with: .automatic)`

By the way Thanks for you efforts and Interest.

**Comment by younatics** [comment]
Great! Thank you for contributing this library :)
